export const browserCoreExamples = [
  "ultraclaw browser status",
  "ultraclaw browser start",
  "ultraclaw browser stop",
  "ultraclaw browser tabs",
  "ultraclaw browser open https://example.com",
  "ultraclaw browser focus abcd1234",
  "ultraclaw browser close abcd1234",
  "ultraclaw browser screenshot",
  "ultraclaw browser screenshot --full-page",
  "ultraclaw browser screenshot --ref 12",
  "ultraclaw browser snapshot",
  "ultraclaw browser snapshot --format aria --limit 200",
  "ultraclaw browser snapshot --efficient",
  "ultraclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "ultraclaw browser navigate https://example.com",
  "ultraclaw browser resize 1280 720",
  "ultraclaw browser click 12 --double",
  'ultraclaw browser type 23 "hello" --submit',
  "ultraclaw browser press Enter",
  "ultraclaw browser hover 44",
  "ultraclaw browser drag 10 11",
  "ultraclaw browser select 9 OptionA OptionB",
  "ultraclaw browser upload /tmp/ultraclaw/uploads/file.pdf",
  'ultraclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "ultraclaw browser dialog --accept",
  'ultraclaw browser wait --text "Done"',
  "ultraclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "ultraclaw browser console --level error",
  "ultraclaw browser pdf",
];
